### ISSUE TITLE
[LOC]Document(ja-jp) is not translated. 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp.ja-jp#31]
![using-the-visual-layer-with-windows-forms_j](https://user-images.githubusercontent.com/40815708/60878531-da148b00-a27a-11e9-859d-daab8b916d54.png)

https://docs.microsoft.com/ja-jp/windows/apps/desktop/modernize/using-the-visual-layer-with-windows-forms

**Comment by lichasu** [comment]
Hello, @hyoshioka0128 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windows-uwp/issues/1785.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
