### ISSUE TITLE
[LOC]Document(ja-jp) is not translated.

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp.ja-jp#51]
related: #31

![accessibility_j](https://user-images.githubusercontent.com/40815708/61177812-ba81b780-a618-11e9-81e5-8732ab8b05e1.png)

https://docs.microsoft.com/ja-jp/windows/apps/accessibility

**Comment by lichasu** [comment]
Hello, @hyoshioka0128

Thank you for your feedback. 

We are actively reviewing your comments and will get back to you soon. 

Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/windows-uwp/issues/1822

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
